---
# tasks file for el_repo_version
- name: Include specific CentOS version variables
  include_vars:
    file: "{{ ansible_distribution | lower }}{{ ansible_distribution_major_version }}.yml"

- name: Disable CentOS Base repositories
  ini_file:
    dest: "{{ el_repo_version_repo_file_base }}"
    section: "{{ item }}"
    option: enabled
    value: 0
  loop: "{{ el_repo_version_repos }}"

- name: Enable CentOS Vault repositories
  yum_repository:
    name: "C{{ el_repo_version }}-{{ item }}"
    description: "CentOS Vault repository for {{ el_repo_version }}"
    file: "{{ el_repo_version_repo_file_name_vault }}"
    baseurl: "http://vault.centos.org/{{ el_repo_version }}/{{ item }}/$basearch/"
    gpgcheck: true
    gpgkey: file:///etc/pki/rpm-gpg/RPM-GPG-KEY-CentOS-7
  loop: "{{ el_repo_version_repos }}"
