---
# tasks file for el_repo_version
- name: Include specific CentOS version variables
  include_vars:
    file: "{{ ansible_distribution | lower }}{{ ansible_distribution_major_version }}.yml"

- name: Disable CentOS Base repositories
  ini_file:
    dest: "{{ el_repo_version_repo_file_base }}"
    section: "{{ item }}"
    option: enabled
    value: 0
  loop: "{{ el_repo_version_repos }}"

- name: Enable CentOS Vault repositories
  ini_file:
    dest: "{{ el_repo_version_repo_file_vault }}"
    section: "C{{ el_repo_version }}-{{ item }}"
    option: enabled
    value: 1
  loop: "{{ el_repo_version_repos }}"
