---
- name: Install the OpenStack repositories from CentOS
  package:
    name: "centos-release-openstack-{{ rdo_packages_openstack_release }}"
    state: present
  when: rdo_packages_openstack_repo == "centos"
  tags:
    - repo

- name: Install the OpenStack repositories from RDO
  get_url:
    url: "{{ item.url }}"
    dest: "{{ item.file }}"
    mode: 0644
    owner: root
    group: root
  loop:
    - file: "/etc/yum.repos.d/delorean-{{ rdo_packages_openstack_release }}.repo"
      url: "https://trunk.rdoproject.org/centos{{ rdo_packages_centos_version }}-{{ rdo_packages_openstack_release }}/{{ rdo_packages_rdo_branch }}/delorean.repo"
    - file: "/etc/yum.repos.d/delorean-deps-{{ rdo_packages_openstack_release }}.repo"
      url: "https://trunk.rdoproject.org/centos{{ rdo_packages_centos_version }}-{{ rdo_packages_openstack_release }}/delorean-deps.repo"
  when: rdo_packages_openstack_repo == "rdo"
  tags:
    - repo

- name: Register Red Hat subscriptions
  redhat_subscription:
    state: present
    username: "{{ rdo_packages_rh_user }}"
    password: "{{ rdo_packages_rh_pass }}"
    auto_attach: true
  when: rdo_packages_openstack_repo == "rhosp"
  tags:
    - repo

- name: Install the OpenStack repositories from Red Hat (RHOSP < 15)
  rhsm_repository:
    name: "{{ item }}"
  loop:
    - rhel-7-server-rpms
    - rhel-7-server-extras-rpms
    - rhel-7-server-rh-common-rpms
    - rhel-ha-for-rhel-7-server-rpms
    - rhel-7-server-nfv-rpms
    - rhel-7-server-rhceph-3-tools-rpms
    - rhel-7-server-rhceph-3-mon-rpms
    - rhel-7-server-rhceph-3-osd-rpms
    - "rhel-7-server-openstack-{{ rdo_packages_openstack_release }}-rpms"
  when:
    - rdo_packages_openstack_repo == "rhosp"
    - rdo_packages_openstack_release < 15
  tags:
    - repo

- name: Install the OpenStack repositories from Red Hat (RHOSP >= 15)
  rhsm_repository:
    name: "{{ item }}"
    state: present
  loop:
    - rhel-8-for-x86_64-baseos-eus-rpms
    - rhel-8-for-x86_64-appstream-rpms
    - rhel-8-for-x86_64-highavailability-eus-rpms
    - "openstack-{{ rdo_packages_openstack_release }}-for-rhel-8-x86_64-rpms"
    - fast-datapath-for-rhel-8-x86_64-rpms
  when:
    - rdo_packages_openstack_repo == "rhosp"
    - rdo_packages_openstack_release >= 15
  tags:
    - repo

- name: Run RHOSP 15/16 specific tasks
  when:
    - rdo_packages_openstack_repo == "rhosp"
    - (rdo_packages_openstack_release == 15) or (rdo_packages_openstack_release == 16)
  block:
    - name: Pin RHEL packages to the 8.1 release
      redhat_subscription:
        username: "{{ rh_user }}"
        password: "{{ rh_pass }}"
        release: 8.1
        state: present

    - name: Install the Ansible repository for RHOSP 16
      rhsm_repository:
        name: ansible-2.8-for-rhel-8-x86_64-rpms
        state: present
