---
- name: Converge
  hosts: all
  tasks:
    - name: "Include tripleo_heat_templates"
      include_role:
        name: "tripleo_heat_templates"
      vars:
        tht_controller_nodes:
          - hostname: controller0
            address:  192.168.24.16
        tht_compute_nodes:
          - hostname: compute0
            address: 192.168.24.17
