---
- name: Install TripleO packages
  package:
    name: "{{ undercloud_packages }}"
    state: present

- name: Create the stack group
  group:
    name: stack
    state: present

- name: Create the stack user
  user:
    name: stack
    group: stack
    state: present

- name: Create a sudo configuration file for the stack user
  copy:
    content: "stack ALL=(root) NOPASSWD:ALL"
    dest: /etc/sudoers.d/stack
    mode: 0440
    owner: root
    group: root

- name: Stat the /usr/share/instack-undercloud/undercloud.conf.sample file
  stat:
    path: /usr/share/instack-undercloud/undercloud.conf.sample
  register: undercloud_instack_conf

- name: Set /usr/share/instack-undercloud as the configuration path
  set_fact:
    undercloud_conf_sample_path: /usr/share/instack-undercloud
  when: undercloud_instack_conf.stat.exists

- name: Set /usr/share/python-tripleoclient as the configuration path
  set_fact:
    undercloud_conf_sample_path: /usr/share/python-tripleoclient
  when: not undercloud_instack_conf.stat.exists

- name: Copy sample Undercloud configuration
  copy:
    src: "{{ undercloud_conf_sample_path }}/undercloud.conf.sample"
    dest: /home/stack/undercloud.conf
    mode: 0600
    owner: stack
    group: stack
    remote_src: true
    force: false

- name: Enable the fake/manual power management driver in Ironic
  ini_file:
    path: /home/stack/undercloud.conf
    section: "{{ item.section }}"
    option: "{{ item.option }}"
    # By default, the other drivers listed here (besides manual-management) are enabled.
    value: "{{ item.value }}"
  loop: "{{ undercloud_config }}"

- name: Install the Undercloud services (this can take up to 1 hour)
  command: openstack undercloud install
  become: true
  become_user: stack
  when: undercloud_install

- name: Download and upload images to Glance
  include_tasks:
    file: undercloud_glance.yml
    apply:
      become: true
      become_user: stack
  when: undercloud_upload_images
