---
# tasks file for tripleo_heat_templates
- name: Create the tempalte directory
  file:
    path: "{{ tht_save_dir }}"
    state: directory

- name: Generate the roles_data file
  template:
    src: "roles_data_{{ tht_release }}.yml.j2"
    dest: "{{ tht_save_dir }}/roles_data_{{ tht_release }}.yml"

- name: Generate the predeployed THT file
  template:
    src: predeployed.yml.j2
    dest: "{{ tht_save_dir }}/predeployed.yml"
  when: tht_predeployed

- name: Generate the Overcloud deploy script
  template:
    src: overcloud_deploy.sh.j2
    dest: "{{ tht_save_dir }}/overcloud_deploy.sh"
    mode: 0755

- debug:
    msg: "All files have been saved to {{ tht_save_dir }}"
