---
# tasks file for tripleo_heat_templates
- name: Create the template directory
  file:
    path: "{{ tht_save_dir }}"
    state: directory

- name: Generate the roles_data file
  template:
    src: "roles_data.yml.j2"
    dest: "{{ tht_save_dir }}/roles_data.yml"

- name: Generate the predeployed THT settings file
  template:
    src: predeployed.yml.j2
    dest: "{{ tht_save_dir }}/predeployed.yml"
  when: tht_predeployed

- name: Generate the predeployed THT settings file
  template:
    src: enable-swap.yaml.j2
    dest: "{{ tht_save_dir }}/enable-swap.yaml"
  when: tht_swap

- name: Generate the common THT settings file
  template:
    src: common.yml.j2
    dest: "{{ tht_save_dir }}/common.yml"

- name: Copy the custom net-config layout over
  copy:
    src: "net-config-nic1-public-nic2-ctlplane-{{ item }}.yaml"
    dest: "{{ tht_save_dir }}/"
  loop:
    - queens
    - train

- name: Generate the Overcloud deploy script
  template:
    src: overcloud_deploy.sh.j2
    dest: "{{ tht_save_dir }}/overcloud_deploy.sh"
    mode: 0755

- debug:
    msg: "All files have been saved to {{ tht_save_dir }}"
